add this file in src/test/resources 
 
base.url=https://anvay-pod-2-1.onrender.com/
browser=chrome
implicit.wait=10
explicit.wait=15
page.load.timeout=30
report.path=test-outputs/reports/ExtentReport.html
screenshot.path=test-outputs/screenshots/
env=prod
 
admin.username=admin@anvay.com
admin.password=Admin@123
 
student.username=abhiram@example.com
student.password=123456
 
institute.username=kumar@anvay.com
institute.password=Admin@123
 
validation.test.email=example@abc.com
validation.test.password=12345678
 
event.club=Coding Club
event.title=Hackathon 2026
event.category=Technical
event.contact=9876543210
event.start.date=2026-12-01T10:00
event.location=Main Lab
 
 
file name: config.properties
 
